# Generated by Django 4.2.7 on 2023-11-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='name2',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='name1',
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_no',
            field=models.CharField(max_length=10),
        ),
    ]
