# Generated by Django 4.2.7 on 2023-12-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_rename_name_student_name2_rename_name_teacher_name1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer science'), ('BCA', 'computer application'), ('FT', 'Food technology'), ('P', 'physics'), ('M', 'maths')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer science'), ('BCA', 'computer application'), ('FT', 'Food technology'), ('P', 'physics'), ('M', 'maths')], max_length=30),
        ),
    ]
