# Generated by Django 4.2.7 on 2023-12-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_student_student_name_teacher_teacher_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer science'), ('BCA', 'computer application'), ('FT', 'Food technology'), ('Physics', 'physics'), ('Maths', 'maths')], max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('CS', 'Computer science'), ('BCA', 'computer application'), ('FT', 'Food technology'), ('Physics', 'physics'), ('Maths', 'maths')], max_length=30),
        ),
    ]
