# Generated by Django 4.2.7 on 2023-12-08 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_alter_student_department_alter_teacher_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=50)),
                ('club_logo', models.FileField(upload_to='images/')),
                ('staff_incharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.teacher')),
            ],
        ),
    ]
