# Generated by Django 4.2.7 on 2023-12-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_remove_club_club_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_logo',
            field=models.FileField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
