# Generated by Django 4.2.7 on 2023-12-13 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0007_club_club_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('club_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.club')),
            ],
        ),
    ]
