# Generated by Django 4.2.7 on 2023-12-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0008_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
