# Generated by Django 4.2.7 on 2023-12-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('feedback', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
