# Generated by Django 4.2.7 on 2024-01-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0011_feedback_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='club_name',
            new_name='club',
        ),
    ]
