# Generated by Django 4.2.7 on 2024-01-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0012_rename_club_name_event_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='club',
            new_name='club1',
        ),
    ]
