# Generated by Django 4.2.7 on 2024-02-03 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0014_joinrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('approve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.joinrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.student')),
            ],
        ),
    ]
